/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'yooyoico\'">' + entity + '</span>' + html;
	}
	var icons = {
		'ico-about': '&#xe600;',
		'ico-add': '&#xe601;',
		'ico-arrows-down': '&#xe602;',
		'ico-arrows-left': '&#xe603;',
		'ico-arrows-right': '&#xe604;',
		'ico-arrows-up': '&#xe605;',
		'ico-beizhu': '&#xe606;',
		'ico-bell': '&#xe607;',
		'ico-book': '&#xe608;',
		'ico-browse': '&#xe609;',
		'ico-building': '&#xe60a;',
		'ico-bus': '&#xe60b;',
		'ico-card': '&#xe60c;',
		'ico-choose-off': '&#xe60d;',
		'ico-choose-on': '&#xe60e;',
		'ico-chufa': '&#xe60f;',
		'ico-chuli': '&#xe610;',
		'ico-circle': '&#xe611;',
		'ico-code': '&#xe612;',
		'ico-coin': '&#xe613;',
		'ico-collection': '&#xe614;',
		'ico-coupons': '&#xe615;',
		'ico-crown': '&#xe616;',
		'ico-danxuan-off': '&#xe617;',
		'ico-danxuan-on': '&#xe618;',
		'ico-distance': '&#xe619;',
		'ico-doublearrows-down': '&#xe61a;',
		'ico-doublearrows-up': '&#xe61b;',
		'ico-download': '&#xe61c;',
		'ico-editor': '&#xe61d;',
		'ico-endclock': '&#xe61e;',
		'ico-favorites': '&#xe61f;',
		'ico-favorites-sel': '&#xe620;',
		'ico-faxian': '&#xe621;',
		'ico-flag': '&#xe622;',
		'ico-flower': '&#xe623;',
		'ico-friends': '&#xe624;',
		'ico-gesture': '&#xe625;',
		'ico-home': '&#xe626;',
		'ico-info': '&#xe627;',
		'ico-information': '&#xe628;',
		'ico-introduce': '&#xe629;',
		'ico-jieshao': '&#xe62a;',
		'ico-lishiclock': '&#xe62b;',
		'ico-location': '&#xe62c;',
		'ico-location-sel': '&#xe62d;',
		'ico-lock': '&#xe62e;',
		'ico-map_bus': '&#xe62f;',
		'ico-map_car': '&#xe630;',
		'ico-map_walk': '&#xe631;',
		'ico-miaosha': '&#xe632;',
		'ico-minus': '&#xe633;',
		'ico-notice1': '&#xe634;',
		'ico-ok': '&#xe635;',
		'ico-ok-sel': '&#xe636;',
		'ico-oneyuan': '&#xe637;',
		'ico-order': '&#xe638;',
		'ico-package': '&#xe639;',
		'ico-passenger': '&#xe63a;',
		'ico-phone': '&#xe63b;',
		'ico-qq': '&#xe63c;',
		'ico-question': '&#xe63d;',
		'ico-question-sel': '&#xe63f;',
		'ico-record': '&#xe640;',
		'ico-ring_star': '&#xe641;',
		'ico-riqi': '&#xe642;',
		'ico-route': '&#xe643;',
		'ico-scenery': '&#xe644;',
		'ico-scope': '&#xe645;',
		'ico-screening': '&#xe646;',
		'ico-search': '&#xe647;',
		'ico-service': '&#xe648;',
		'ico-share': '&#xe649;',
		'ico-shibai': '&#xe64a;',
		'ico-sina': '&#xe64b;',
		'ico-sort': '&#xe64c;',
		'ico-space': '&#xe64d;',
		'ico-star': '&#xe64e;',
		'ico-successful': '&#xe64f;',
		'ico-sun': '&#xe650;',
		'ico-tag': '&#xe651;',
		'ico-telephone': '&#xe652;',
		'ico-ticket': '&#xe653;',
		'ico-time': '&#xe654;',
		'ico-trash': '&#xe655;',
		'ico-unlock': '&#xe656;',
		'ico-user': '&#xe657;',
		'ico-user2': '&#xe658;',
		'ico-vip': '&#xe659;',
		'ico-vipbiaoqian': '&#xe65a;',
		'ico-wallet': '&#xe65b;',
		'ico-wechat': '&#xe65c;',
		'ico-xuzhi_anquan': '&#xe65d;',
		'ico-xuzhi_feiyong': '&#xe65e;',
		'ico-xuzhi_tishi': '&#xe65f;',
		'ico-xuzhi_yuding': '&#xe660;',
		'ico-youbi': '&#xe661;',
		'ico-youhuijingqu': '&#xe662;',
		'ico-youyou-coin': '&#xe663;',
		'ico-zhiyin': '&#xe664;',
		'ico-hotspring': '&#xe933;',
		'ico-weekend': '&#xe934;',
		'ico-family': '&#xe935;',
		'ico-scenic': '&#xe936;',
		'ico-pc_del2': '&#xe932;',
		'ico-heart_solid': '&#xe92e;',
		'ico-mic': '&#xe92f;',
		'ico-traffic-40': '&#xe930;',
		'ico-shopping_car': '&#xe931;',
		'ico-vip_type': '&#xe92d;',
		'ico-arrows-s-up': '&#xe92b;',
		'ico-arrows-s-down': '&#xe92c;',
		'ico-triangle_yes': '&#xe92a;',
		'ico-pc_succeed': '&#xe929;',
		'ico-pc_account': '&#xe900;',
		'ico-pc_android': '&#xe901;',
		'ico-pc_attention': '&#xe902;',
		'ico-pc_calendar': '&#xe903;',
		'ico-pc_calendar_left': '&#xe904;',
		'ico-pc_calendar_right': '&#xe905;',
		'ico-pc_car': '&#xe906;',
		'ico-pc_circle_close': '&#xe907;',
		'ico-pc_circle_vip': '&#xe908;',
		'ico-pc_cost': '&#xe909;',
		'ico-pc_del': '&#xe90a;',
		'ico-pc_dimension': '&#xe90b;',
		'ico-pc_dinner': '&#xe90c;',
		'ico-pc_eye_close': '&#xe90d;',
		'ico-pc_eye_open': '&#xe90e;',
		'ico-pc_fenxiang': '&#xe90f;',
		'ico-pc_forget': '&#xe910;',
		'ico-pc_heart': '&#xe911;',
		'ico-pc_hill': '&#xe912;',
		'ico-pc_hotel': '&#xe913;',
		'ico-pc_ios': '&#xe914;',
		'ico-pc_jieri': '&#xe915;',
		'ico-pc_know': '&#xe916;',
		'ico-pc_nogoods': '&#xe917;',
		'ico-pc_number_bg': '&#xe918;',
		'ico-pc_password': '&#xe919;',
		'ico-pc_plane': '&#xe91a;',
		'ico-pc_qiandao': '&#xe91b;',
		'ico-pc_seckill': '&#xe91c;',
		'ico-pc_service_phone': '&#xe91d;',
		'ico-pc_top': '&#xe91e;',
		'ico-pc_traffic': '&#xe91f;',
		'ico-pc_triangle_down': '&#xe920;',
		'ico-pc_triangle_up': '&#xe921;',
		'ico-pc_user_collection': '&#xe922;',
		'ico-pc_user_exit': '&#xe923;',
		'ico-pc_user_home': '&#xe924;',
		'ico-pc_user_order': '&#xe925;',
		'ico-pc_user_setting': '&#xe926;',
		'ico-pc_user_ziliao': '&#xe927;',
		'ico-pc_weixin': '&#xe928;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/ico-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
